package com.database.entity;

import java.io.Serializable;

public class Player implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.name
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.id
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.exp
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private Integer exp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.loc
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private Integer loc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.occupation
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private Integer occupation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.equip
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private String equip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.money
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.friend
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private String friend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.roleId
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.exp
     *
     * @return the value of player.exp
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.exp
     *
     * @param exp the value for player.exp
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.loc
     *
     * @return the value of player.loc
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public Integer getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.loc
     *
     * @param loc the value for player.loc
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setLoc(Integer loc) {
        this.loc = loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.occupation
     *
     * @return the value of player.occupation
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public Integer getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.occupation
     *
     * @param occupation the value for player.occupation
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setOccupation(Integer occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.equip
     *
     * @return the value of player.equip
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public String getEquip() {
        return equip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.equip
     *
     * @param equip the value for player.equip
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setEquip(String equip) {
        this.equip = equip == null ? null : equip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.money
     *
     * @return the value of player.money
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.money
     *
     * @param money the value for player.money
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.friend
     *
     * @return the value of player.friend
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public String getFriend() {
        return friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.friend
     *
     * @param friend the value for player.friend
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setFriend(String friend) {
        this.friend = friend == null ? null : friend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.roleId
     *
     * @return the value of player.roleId
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.roleId
     *
     * @param roleid the value for player.roleId
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", id=").append(id);
        sb.append(", exp=").append(exp);
        sb.append(", loc=").append(loc);
        sb.append(", occupation=").append(occupation);
        sb.append(", equip=").append(equip);
        sb.append(", money=").append(money);
        sb.append(", friend=").append(friend);
        sb.append(", roleid=").append(roleid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}