package com.database.mapper;

import com.database.entity.Bag;
import com.database.entity.BagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bag
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    long countByExample(BagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bag
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    int deleteByExample(BagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bag
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    int insert(Bag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bag
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    int insertSelective(Bag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bag
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    List<Bag> selectByExample(BagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bag
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") Bag record, @Param("example") BagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bag
     *
     * @mbg.generated Sun Jul 26 21:12:57 CST 2020
     */
    int updateByExample(@Param("record") Bag record, @Param("example") BagExample example);
}