
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mmorpg?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: password
#    type: com.alibaba.druid.pool.DruidDataSource
#    #spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
#
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  check-config-location: true
#  type-aliases-package: com.database